[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Specific redirects for simplified test functions
[[redirects]]
  from = "/api/simple-generate-leads"
  to = "/.netlify/functions/simple-generate-leads"
  status = 200

[[redirects]]
  from = "/api/simple-check-status"
  to = "/.netlify/functions/simple-check-status"
  status = 200

# Test JSON function redirect
[[redirects]]
  from = "/api/test-json"
  to = "/.netlify/functions/test-json"
  status = 200
